server:
  port: 9001

spring:
  data:
    mongodb:
      uri: mongodb://admin:libra123@localhost:27017/toldb?authSource=admin
    redis:
      host: localhost
      port: 6379
      password: libra123
      database: 0
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 100
          max-wait: 4000
        shutdown-timeout: 5000
springdoc:
  api-docs:
    path: /v1/api-doc
  swagger-ui:
    path: /document
    default-models-expand-depth: -1

logging:
  file:
    name: logback
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: INFO
          redis:
            core:
              RedisTemplate: INFO
