server:
  port: 9001

spring:
  data:
    mongodb:
      database: toldb
      port: 27017
    redis:
      host: localhost
      port: 6379
      password: libra123
      database: 0
      lettuce:
        pool:
          min-idle: 10
          max-active: 100
          max-idle: 100
          max-wait: 4000
        shutdown-timeout: 5000
springdoc:
  api-docs:
    path: /v1/api
  swagger-ui:
    path: /document

logging:
  file:
    name: logback

